"""Initial clean setup

Revision ID: 007801f33906
Revises: 
Create Date: 2026-03-27 20:38:43.832981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007801f33906'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diet_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('goal', sa.String(length=64), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('bmi_category', sa.String(length=64), nullable=True),
    sa.Column('calorie_goal', sa.Integer(), nullable=True),
    sa.Column('diet_type', sa.String(length=64), nullable=True),
    sa.Column('insight', sa.Text(), nullable=True),
    sa.Column('foods_json', sa.Text(), nullable=True),
    sa.Column('meal_plan_json', sa.Text(), nullable=True),
    sa.Column('macro_warning', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diet_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diet_suggestions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diet_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diet_suggestions_user_id'))

    op.drop_table('diet_suggestions')
    # ### end Alembic commands ###
