"""initial migration

Revision ID: 10655e4672be
Revises: 
Create Date: 2026-03-17 22:58:49.615609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10655e4672be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.String(length=120), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.String(length=50), nullable=False),
    sa.Column('goal', sa.String(length=30), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_logs')
    # ### end Alembic commands ###
