"""initial fresh local state

Revision ID: 2f1a1ca015cb
Revises: 
Create Date: 2026-03-17 12:54:13.566153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f1a1ca015cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.String(length=120), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.String(length=50), nullable=False),
    sa.Column('goal', sa.String(length=30), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('viewer_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food_items.id'], ),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('recently_viewed', schema=None) as batch_op:
        batch_op.alter_column('viewed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recently_viewed', schema=None) as batch_op:
        batch_op.alter_column('viewed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    op.drop_table('food_views')
    op.drop_table('meal_logs')
    # ### end Alembic commands ###
