"""Add diet_type to food_items

Revision ID: 4844a8aae071
Revises: 
Create Date: 2026-03-17 16:00:57.025416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4844a8aae071'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('food_categories')  # <-- leave commented if not dropping

    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diet_type', sa.String(length=50), nullable=True))
        batch_op.add_column(
            sa.Column(
                'availability_status', 
                sa.String(length=20), 
                nullable=False, 
                server_default='available'  # <-- temporary default for existing rows
            )
        )
        batch_op.add_column(sa.Column('order_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('view_count', sa.Integer(), nullable=True))
        batch_op.alter_column('provider_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('food_items_category_id_fkey'), type_='foreignkey')
        batch_op.drop_column('fiber')
        batch_op.drop_column('diet_tags')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('category_id')
        batch_op.drop_column('serving_size')
        batch_op.drop_column('sugar')
        batch_op.drop_column('sodium')
        batch_op.drop_column('is_active')

        # Remove server_default after adding column
        batch_op.alter_column('availability_status', server_default=None)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('account_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('account_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
        batch_op.alter_column('is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('sodium', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sugar', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('serving_size', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('diet_tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fiber', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('food_items_category_id_fkey'), 'food_categories', ['category_id'], ['id'])
        batch_op.alter_column('provider_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('view_count')
        batch_op.drop_column('order_count')
        batch_op.drop_column('availability_status')
        batch_op.drop_column('diet_type')

    op.create_table('food_categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('food_categories_pkey')),
    sa.UniqueConstraint('name', name=op.f('food_categories_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
