"""add goal to meal_logs

Revision ID: 4aef912b283b
Revises: c08806151655
Create Date: 2026-03-16 23:37:42.541807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aef912b283b'
down_revision = 'c08806151655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_logs', schema=None) as batch_op:
        batch_op.drop_column('goal')

    # ### end Alembic commands ###
