"""update food item nutrition fields

Revision ID: 75370e58754c
Revises: 91f8beff9358
Create Date: 2026-03-09 21:12:27.526634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75370e58754c'
down_revision = '91f8beff9358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('protein', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carbs', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fat', sa.Float(), nullable=True))
        batch_op.drop_column('nutrition_info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nutrition_info', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('fat')
        batch_op.drop_column('carbs')
        batch_op.drop_column('protein')
        batch_op.drop_column('calories')

    # ### end Alembic commands ###
