"""sync meal_logs columns

Revision ID: 835b65a796f9
Revises: 
Create Date: 2026-04-10 19:19:27.499744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835b65a796f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fitness_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_weight', sa.Float(), nullable=False),
    sa.Column('target_weight', sa.Float(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('activity_level', sa.Float(), nullable=False),
    sa.Column('daily_calories', sa.Integer(), nullable=False),
    sa.Column('tdee', sa.Integer(), nullable=True),
    sa.Column('daily_deficit', sa.Integer(), nullable=True),
    sa.Column('ai_result_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fitness_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fitness_goals_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('meal_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('protein', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('carbs', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('nutrition_source', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('nutrition_confidence', sa.String(length=10), nullable=True))
        batch_op.add_column(
    sa.Column('is_ai_estimated', sa.Boolean(), nullable=False, server_default='false')
)
        batch_op.add_column(sa.Column('parsed_items_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_logs', schema=None) as batch_op:
        batch_op.drop_column('parsed_items_json')
        batch_op.drop_column('is_ai_estimated')
        batch_op.drop_column('nutrition_confidence')
        batch_op.drop_column('nutrition_source')
        batch_op.drop_column('fat')
        batch_op.drop_column('carbs')
        batch_op.drop_column('protein')
        batch_op.drop_column('calories')

    with op.batch_alter_table('fitness_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fitness_goals_user_id'))

    op.drop_table('fitness_goals')
    # ### end Alembic commands ###
