"""initial

Revision ID: c08806151655
Revises: 
Create Date: 2026-03-15 14:38:28.583089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c08806151655'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dietary_preferences', schema=None) as batch_op:
        batch_op.drop_column('goal')

    with op.batch_alter_table('meal_logs', schema=None) as batch_op:
        batch_op.alter_column('food_name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.drop_column('ai_analyzed')
        batch_op.drop_column('notes')
        batch_op.drop_column('carbs')
        batch_op.drop_column('protein')
        batch_op.drop_column('fat')
        batch_op.drop_column('calories')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('protein', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('carbs', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ai_analyzed', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.alter_column('food_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('dietary_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
