"""empty message

Revision ID: e2468a06d8ba
Revises: 
Create Date: 2026-04-08 13:51:12.650177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2468a06d8ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diet_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('goal', sa.String(length=64), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('bmi_category', sa.String(length=64), nullable=True),
    sa.Column('calorie_goal', sa.Integer(), nullable=True),
    sa.Column('diet_type', sa.String(length=64), nullable=True),
    sa.Column('insight', sa.Text(), nullable=True),
    sa.Column('foods_json', sa.Text(), nullable=True),
    sa.Column('meal_plan_json', sa.Text(), nullable=True),
    sa.Column('macro_warning', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diet_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diet_suggestions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('food_nutrition_cache', schema=None) as batch_op:
        batch_op.drop_index('ix_food_nutrition_cache_normalized_name')

    op.drop_table('food_nutrition_cache')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_nutrition_cache',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('normalized_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('calories', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('protein', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('carbs', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('nutrition_source', sa.VARCHAR(length=50), server_default=sa.text("'ai_estimate'::character varying"), autoincrement=False, nullable=False),
    sa.Column('nutrition_confidence', sa.VARCHAR(length=20), server_default=sa.text("'medium'::character varying"), autoincrement=False, nullable=False),
    sa.Column('nutrition_basis', sa.VARCHAR(length=20), server_default=sa.text("'100g'::character varying"), autoincrement=False, nullable=False),
    sa.Column('is_ai_estimated', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('last_nutrition_sync', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='food_nutrition_cache_pkey')
    )
    with op.batch_alter_table('food_nutrition_cache', schema=None) as batch_op:
        batch_op.create_index('ix_food_nutrition_cache_normalized_name', ['normalized_name'], unique=False)

    with op.batch_alter_table('diet_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diet_suggestions_user_id'))

    op.drop_table('diet_suggestions')
    # ### end Alembic commands ###
